### ISSUE TITLE
seeThru combined with ar.js and a-frame

### ISSUE THREAD

**Issue by jacogaz** [m90/seeThru#58]
Hello! I recently found this library which almost saved my life because I needed an alpha mp4 video that could display on a website.

I tried to use with this ar.js and a-frame to play the video when a hiro marker shows, so I can simulate a VR experience... (kinda).
The question is, have you tried before? I'am following a-frame instructions to play a video and also ar.js instructions to catch the hiro-marker but the only thing I got is to allow my camera and play the alpha video over the screen.

I think the problem is that seeThru is not able to create the alpha video and that's why the video that play over the hiro marker is the two video (the black-screen one, and the white-silhouette).

If you have experienced same issues or similar issues please feel free to answer this. I tried almost everyting.

I uploaded my code, just an index.html, seeThru.min.js, the pattern(hiro-marker) and styles.css which has nothing anyway.

[github_issue.zip](https://github.com/m90/seeThru/files/3272130/github_issue.zip)

**Comment by m90** [comment]
I cannot run your example as the video file is 404ing, but I would assume you need to tell ar.js about what it is supposed to handle (which is the canvas element bein created instead of the video).

I think the ar.js people might have more ideas about how to implement this than I do as the question is rather about how to target the output produced by `seeThru` correctly.

**Comment by jacogaz** [comment]
Yees... sorry I didn't let me upload the video...

The problem is that seeThru is not creating the alpha video, because when I target the hiro marker shows me the double height video...

Do you think I have to target the canvas instead of targeting the video?

Thank you in advance

**Comment by m90** [comment]
I have a hard time giving support on how to work with ar.js, but I would look for the following:

- calling seeThru.create *asynchronously* creates a canvas element that will be used to display the video. It's one of the arguments passed to the ready callback. You can also inspect the DOM to find where that element is being put.
- once the ready callback is called, you will need to make ar.js use that element instead of the video
- this might mean you will have to put the video outside of the ar.js tag and then move the canvas in there when it is ready

Specific questions about how to do that are ar.js related and I would probably ask there in case you need further support as all I can do here is guess.

**Comment by jacogaz** [comment]
Ok, I see the point, it clarifies me about certain things.

Thank you so much for worrying about this, I'll go further with ar.js

**Comment by m90** [comment]
Closing this as it seems to be solved. In case you need further help here, feel free to reopen.
