### ISSUE TITLE
cannot import cdn keep erroring out

### ISSUE THREAD

**Issue by lv2lrn4lf** [m90/seeThru#78]
cannot javascript import cdn keep erroring out:

```
//import "https://unpkg.com/seethru@4/dist/seeThru.min.js";
//import "https://cdn.jsdelivr.net/npm/seethru@2/dist/seeThru.min.js";
import "https://unpkg.com/seethru@latest/dist/seeThru.min.js";
```

in brwoser get error:
```
Uncaught TypeError: e is undefined
```

I just tried it via:

```
<script src="https://cdn.jsdelivr.net/npm/seethru@4/dist/seeThru.min.js"></script>
```

and it throw the same error!

**Comment by lv2lrn4lf** [comment]
@m90 my bad i forgot to comment out the import when I tried the script version... so how hard would it to do a esm module version it just adding the export statement right and how fast can you have it in cdn? i can add a export statement in there... unless there mroe.

**Comment by m90** [comment]
To be honest I don't know how hard that would be as I'm not doing too much JavaScript anymore recently and have never really worked with ESM.

I would assume one would have to do the following:

- "Rewrite" the script to be ESM (not too hard as it's a single file)
- Adjust the build so that it creates an UMD version as well as an ESM version
- Add necessary fields to `package.json`
